language: objective-c
osx_image: xcode9.0
before_install:
  - carthage bootstrap --no-use-binaries --platform ios
script:
  - xcodebuild clean build test -scheme 'RxActivityIndicator iOS' -destination "platform=iOS Simulator,name=iPhone 6S" -enableCodeCoverage YES | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'RxActivityIndicator'

